builds:
  - id: fhome
    binary: fhome
    main: ./cmd/fhome
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

  - id: fhomed
    binary: fhomed
    main: ./cmd/fhomed
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - id: fhome
    name_template: 'fhome_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - fhome
    files:
      - LICENSE
      - README.md
      - autocomplete/zsh_autocomplete_fhome
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: fhomed
    name_template: 'fhomed_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - fhomed
    files:
      - LICENSE
      - README.md
      - autocomplete/zsh_autocomplete_fhomed
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

changelog:
  skip: true

brews:
  - name: fhome
    ids:
      - fhome
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    license: MIT
    install: |
      bin.install "fhome"
      zsh_completion.install "autocomplete/zsh_autocomplete_fhome" => "_fhome"

  - name: fhomed
    ids:
      - fhomed
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Background daemon for F&Home
    license: MIT
    install: |
      bin.install "fhomed"
      zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
