version: 2

builds:
  - id: fhome
    binary: fhome
    main: ./cmd/fhome
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: fhomed
    binary: fhomed
    main: ./cmd/fhomed
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: fhome
    name_template: "fhome_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - fhome
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: zip

  - id: fhomed
    name_template: "fhomed_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - fhomed
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: zip

# Required for AUR sources
source:
  enabled: true

changelog:
  disable: true

brews:
  - name: fhome
    ids:
      - fhome
    repository:
      owner: bartekpacia
      name: homebrew-tools
    directory: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    license: MIT
    install: |
      bin.install "fhome"
      generate_completions_from_executable(bin/"fhome", "completion")

  - name: fhomed
    ids:
      - fhomed
    repository:
      owner: bartekpacia
      name: homebrew-tools
    directory: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Background daemon for F&Home
    license: MIT
    install: |
      man_content = `./fhomed docs --format man-with-section`
      File.write("fhomed.1", man_content)

      bin.install "fhomed"
      generate_completions_from_executable(bin/"fhomed", "completion")
      
      man1.install "fhomed.1"

aur_sources:
  - name: fhome
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: git@github.com:bartekpacia/aur.git
    directory: fhome
    commit_msg_template: update fhome to {{ .Tag }}
    prepare: |
      cd "${pkgname}-${pkgver}"
      export GOPATH="${srcdir}"
      go mod download -modcacherw
    build: |
      cd "${pkgname}-${pkgver}"
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      go build -ldflags="-w -s -buildid='' -linkmode=external -X main.version=${pkgver}" .
      chmod +x ./fhome
    package: |
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 fhome "${pkgdir}/usr/bin/fhome"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/fhome/LICENSE"

      # completions
      ./fhome completion bash > completion_bash
      ./fhome completion zsh > completion_zsh
      install -Dm755 completion_bash "${pkgdir}/usr/share/bash-completion/completions/fhome"
      install -Dm755 completion_zsh "${pkgdir}/usr/share/zsh/site-functions/_fhome"

aurs:
  - name: fhome-bin
    ids:
      - fhome
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: git@github.com:bartekpacia/aur.git
    directory: fhome-bin
    commit_msg_template: update fhome to {{ .Tag }}
    package: |
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 fhome "${pkgdir}/usr/bin/fhome"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/fhome/LICENSE"

      # completions
      ./fhome completion bash > completion_bash
      ./fhome completion zsh > completion_zsh
      install -Dm755 completion_bash "${pkgdir}/usr/share/bash-completion/completions/fhome"
      install -Dm755 completion_zsh "${pkgdir}/usr/share/zsh/site-functions/_fhome"

  - name: fhomed-bin
    ids:
      - fhomed
    homepage: https://github.com/bartekpacia/fhome
    description: Background daemon for F&Home
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: git@github.com:bartekpacia/aur.git
    directory: fhomed-bin
    commit_msg_template: update fhomed to {{ .Tag }}
    package: |
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 fhomed "${pkgdir}/usr/bin/fhomed"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/fhomed/LICENSE"

      # completions
      ./fhomed completion bash > completion_bash
      ./fhomed completion zsh > completion_zsh
      install -Dm755 completion_bash "${pkgdir}/usr/share/bash-completion/completions/fhomed"
      install -Dm755 completion_zsh "${pkgdir}/usr/share/zsh/site-functions/_fhomed"

      # man pages
      ./fhomed docs --format man-with-section > fhomed.1
      install -Dm644 fhomed.1 "${pkgdir}/usr/share/man/man1/fhomed.1"
