builds:
  - id: fhome
    binary: fhome
    main: ./cmd/fhome
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: fhomed
    binary: fhomed
    main: ./cmd/fhomed
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: fhome
    name_template: "fhome_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - fhome
    files:
      - LICENSE
      - README.md
      - autocomplete/zsh_autocomplete_fhome
      - autocomplete/bash_autocomplete_fhome
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: fhomed
    name_template: "fhomed_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - fhomed
    files:
      - LICENSE
      - README.md
      - autocomplete/zsh_autocomplete_fhomed
      - autocomplete/bash_autocomplete_fhomed
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true

brews:
  - name: fhome
    ids:
      - fhome
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    license: MIT
    install: |
      bin.install "fhome"
      bash_completion.install "autocomplete/bash_autocomplete_fhome" => "fhome"
      zsh_completion.install "autocomplete/zsh_autocomplete_fhome" => "_fhome"

  - name: fhomed
    ids:
      - fhomed
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Background daemon for F&Home
    license: MIT
    install: |
      bin.install "fhomed"
      bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
      zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"

aurs:
  - name: fhome-bin
    ids:
      - fhome
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    git_url: git@github.com:bartekpacia/aur.git
    directory: fhome-bin
    commit_msg_template: update fhome to {{ .Tag }}
    package: |
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 fhome "${pkgdir}/usr/bin/fhome"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/fhome/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      install -Dm755 autocomplete/bash_autocomplete_fhome "${pkgdir}/usr/share/bash-completion/completions/fhome"
      install -Dm755 autocomplete/zsh_autocomplete_fhome "${pkgdir}/usr/share/zsh/site-functions/_fhome"

      # man pages
      # install -Dm644 "./manpages/mybin.1.gz" "${pkgdir}/usr/share/man/man1/mybin.1.gz"

  - name: fhomed-bin
    ids:
      - fhomed
    homepage: https://github.com/bartekpacia/fhome
    description: Background daemon for F&Home
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    git_url: git@github.com:bartekpacia/aur.git
    directory: fhomed-bin
    commit_msg_template: update fhomed to {{ .Tag }}
    package: |
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 fhomed "${pkgdir}/usr/bin/fhomed"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/fhomed/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      install -Dm755 autocomplete/bash_autocomplete_fhomed "${pkgdir}/usr/share/bash-completion/completions/fhomed"
      install -Dm755 autocomplete/zsh_autocomplete_fhomed "${pkgdir}/usr/share/zsh/site-functions/_fhomed"

      # man pages
      # install -Dm644 "./manpages/mybin.1.gz" "${pkgdir}/usr/share/man/man1/mybin.1.gz"
