services:
  influx-db:
    image: influxdb:2.7-alpine
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: supersecret
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 9uNp_AJQknsl8OWY65VGyAVZ0wpLXrm9Ep9_4L4-LJJWkP4HJxQvgMCd0vIElfFVU-9cIMdPgPGuUZvaDJsn5g==
      DOCKER_INFLUXDB_INIT_ORG: fhome
      DOCKER_INFLUXDB_INIT_BUCKET: main
    volumes:
      - type: volume
        source: fhome-influx-data
        target: /var/lib/influxdb2
      - type: volume
        source: fhome-influx-config
        target: /etc/influxdb2


volumes:
  fhome-influx-data:
  fhome-influx-config:

