#!/bin/bash

# easily source environment variables from .env file
# usage: "source ./src_env"

command cat .env | while read line; do
	if [ -n "$line" ]; then
		export $line
    	printf "export $line\n"
    fi
done
