agents:
  queue: linux-small

steps:
  - label: prepare
    # key: prepare # not needed!
    # branches: master # not needed!
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: |
      go version
      echo "--- Verify code formatting"
      go install mvdan.cc/gofumpt@latest
      test -z "$(gofumpt -l .)"
      echo "--- Run linter"
      go install honnef.co/go/tools/cmd/staticcheck@latest
      staticcheck ./...
      echo "--- Run tests with coverage"
      go test -cover ./...

  - label: format
    key: format
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: |
      echo "~~~ Install formatter"
      go install mvdan.cc/gofumpt@latest
      test -z "$(gofumpt -l .)"
      echo "--- Verify formatting"
      test -z "$(gofumpt -l .)"

  - label: lint
    key: lint
    depends_on: format
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: |
      echo "~~~ Install linter"
      go install honnef.co/go/tools/cmd/staticcheck@latest
      staticcheck ./...
      echo "--- Verify linting"
      test -z "$(staticcheck ./...)"

  - label: test
    key: test
    depends_on: lint
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: |
      echo "--- Run tests with coverage"
      go test -cover ./...
