agents:
  queue: linux-small

steps:
  - label: prepare
    # key: prepare # not needed!
    # branches: master # not needed!
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: |
      go version
      echo "--- Verify code formatting"
      go install mvdan.cc/gofumpt@latest
      test -z "$(gofumpt -l .)"
      echo "--- Run linter"
      go install honnef.co/go/tools/cmd/staticcheck@latest
      staticcheck ./...
      echo "--- Run tests with coverage"
      go test -cover ./...

  - label: build & push fhome-publish OCI image
    key: build-publish-image
    # if_changed: ".buildkite/images/publish/**"
    secrets:
      - MY_BK_REGISTRY_TOKEN
    plugins:
      - docker-login#v3.0.0:
          server: packages.buildkite.com/bartekpacia/my-registry
          username: buildkite
          password-env: MY_BK_REGISTRY_TOKEN
    command: |
      IMAGE=packages.buildkite.com/bartekpacia/my-registry/fhome-publish:v1
      docker build -t "$$IMAGE" .buildkite/images/publish
      docker push "$$IMAGE"

  - label: format
    key: format
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: .buildkite/scripts/format.sh

  - label: lint
    key: lint
    depends_on: format
    plugins:
      - docker#v5.12.0:
          image: golang:1.26-alpine
          workdir: /workspace
    command: .buildkite/scripts/lint.sh

  - block: Publish binaries
    key: publish-gate

  - label: publish
    key: publish
    depends_on: [lint, publish-gate]
    if: build.tag =~ /^v/
    secrets:
      - AUR_SSH_PRIVATE_KEY
      - OP_SERVICE_ACCOUNT_TOKEN
      - MY_BK_REGISTRY_TOKEN
    plugins:
      - docker-login#v3.0.0:
          server: packages.buildkite.com/bartekpacia/my-registry
          username: buildkite
          password-env: MY_BK_REGISTRY_TOKEN
      - docker#v5.12.0:
          image: packages.buildkite.com/bartekpacia/my-registry/fhome-publish:v1
          workdir: /workspace
          propagate-environment: true
          environment:
            - OP_SERVICE_ACCOUNT_TOKEN
            - AUR_SSH_PRIVATE_KEY
    command: .buildkite/scripts/publish.sh

